# Generated by Django 2.0.7 on 2018-07-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('reg_no', models.CharField(max_length=8)),
                ('mail_id', models.CharField(max_length=16)),
                ('degree', models.CharField(max_length=16)),
                ('department', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=64)),
                ('experience', models.IntegerField(max_length=2)),
                ('location', models.CharField(max_length=16)),
                ('linkedin', models.CharField(max_length=16)),
                ('github', models.CharField(max_length=16)),
                ('working_as', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
