# Generated by Django 2.0.7 on 2018-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniinfo',
            name='passed_out',
            field=models.IntegerField(default=2015),
        ),
        migrations.AddField(
            model_name='alumniinfo',
            name='phn_no',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
