# Generated by Django 2.0.7 on 2018-07-23 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180717_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='company',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='degree',
            field=models.CharField(choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH'), ('MBA', 'MBA')], max_length=12),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('ECE', 'ECE'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CSE', 'CSE')], max_length=12),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='experience',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('>5', '>5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='github',
            field=models.CharField(max_length=36, validators=[django.core.validators.RegexValidator(regex='\\w+://github.com+')]),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='linkedin',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^\\w+://+www.linkedin.com+')]),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='location',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='mail_id',
            field=models.CharField(max_length=36, validators=[django.core.validators.RegexValidator(regex='^\\w+@[a-zA-Z_]+?\\.[a-zA-Z]{2,6}')]),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='passed_out',
            field=models.PositiveIntegerField(default=2012),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='phn_no',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='reg_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9A-Z-]+')]),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='working_as',
            field=models.CharField(max_length=12),
        ),
    ]
