# Generated by Django 2.0.7 on 2018-07-23 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180723_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='description',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='experience',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('+6', '+6')], max_length=2),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='github',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(regex='\\w+://+www.github.com+')]),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='linkedin',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(regex='^\\w+://+www.linkedin.com+')]),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='location',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='mail_id',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(regex='^\\w+@[a-zA-Z_]+?\\.[a-zA-Z]{2,6}')]),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='working_as',
            field=models.CharField(max_length=20),
        ),
    ]
