# Generated by Django 2.0.7 on 2018-07-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20180723_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='description',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
