# Generated by Django 2.0.7 on 2018-07-23 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20180723_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='github',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='\\w+://github.com+')]),
        ),
    ]
