# Generated by Django 2.0.7 on 2018-07-23 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20180723_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='company',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='degree',
            field=models.CharField(choices=[('Bachelor Of Technology', 'Bachelor Of Technology'), ('Master Of Technology', 'Master Of Technology'), ('Master Of Buisiness Administration', 'Master Of Buisiness Administration'), ('Master Of Science', 'Master Of Science'), ('Btech Dropout', 'Btech Dropout')], max_length=36),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='location',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='mail_id',
            field=models.CharField(max_length=36, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9\\.\\_]+@[a-z_]+?\\.[a-zA-Z]{2,6}')]),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='name',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='reg_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9A-Za-z]')]),
        ),
    ]
