# Generated by Django 2.0.7 on 2018-07-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20180723_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniinfo',
            name='password',
            field=models.TextField(blank=True, max_length=16, null=True),
        ),
    ]
