# Generated by Django 2.0.7 on 2018-07-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alumniinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
