# Generated by Django 2.0.7 on 2018-08-18 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20180725_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,20}')]),
        ),
    ]
