# Generated by Django 2.0.7 on 2018-08-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('reg_no', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField(default=1)),
                ('phn_no', models.PositiveIntegerField()),
                ('git_hub', models.CharField(max_length=64)),
                ('linkedIn', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=1024)),
                ('usrname', models.CharField(max_length=16)),
                ('pswd', models.CharField(max_length=16)),
            ],
        ),
    ]
