# Generated by Django 2.0.7 on 2018-08-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='dept',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='course',
            field=models.CharField(choices=[('Bachelor Of Technology', 'Bachelor Of Technology'), ('Master Of Technology', 'Master Of Technology'), ('Master Of Buisiness Administration', 'Master Of Buisiness Administration')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='stream',
            field=models.CharField(choices=[('IT', 'IT'), ('ECE', 'ECE'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CSE', 'CSE')], max_length=16, null=True),
        ),
    ]
