# Generated by Django 2.0.7 on 2018-08-18 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180818_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='mail',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=32, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9\\.\\_]+@[a-z_]+?\\.[a-zA-Z]{2,6}')]),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='git_hub',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='\\w+://github.com+')]),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='linkedIn',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='^\\w+://+www.linkedin.com+')]),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='phn_no',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='pswd',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,20}')]),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='reg_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9A-Za-z]')]),
        ),
    ]
