# Generated by Django 2.0.7 on 2018-08-18 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180818_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='course',
            field=models.CharField(choices=[('Bachelor Of Technology', 'Bachelor Of Technology'), ('Master Of Technology', 'Master Of Technology'), ('Master Of Buisiness Administration', 'Master Of Buisiness Administration')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='reg_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9A-Z]')]),
        ),
    ]
